# server {
#     listen 80;

#     server_name _;

#     # Raiz do site
#     root /usr/share/nginx/html;

#     # Para assets estáticos do React
#     location /rack {
#         index index.html;
#         try_files $uri /rack/index.html;
#     }

#     # opcional: se quiser que / também redirecione para /rack
#     location = / {
#         return 302 /rack;
#     }
# }

server {
    listen 80;
    server_name _;

    # Raiz do site - React app
    location /rack {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /rack/index.html;
    }

    # Proxy para API Flask
    location /api {
        proxy_pass http://backend:5000/api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Redirecionar raiz para /rack
    location = / {
        return 302 /rack;
    }
}